[package]
name = "duckme"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0"
actix-files = "0.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
duckdb = { version = "0.9.2", features = ["bundled"] }
chrono = { version = "0.4", features = ["serde"] }
